apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: kubernetes-practices
type: Opaque
stringData:
  MONGO_DB_USER: "admin"
  MONGO_DB_PASS: "password"
  MONGO_DB_URI: "mongodb://admin:password@localhost:27017/database?authMechanism=DEFAULT&authSource=admin"
