apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  namespace: kubernetes-practices
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom: 
        secretKeyRef:
          name: credentials
          key: MONGO_DB_USER
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: credentials
          key: MONGO_DB_PASS
    volumeMounts:
    - name: mongo-storage
      mountPath: /data/db
  volumes:
  - name: mongo-storage
    emptyDir: {}

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: kubernetes-practices
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP