apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kubernetes-practices
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kubernetes-practices-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_DB_URI
          valueFrom: 
            secretKeyRef:
              name: credentials
              key: MONGO_DB_URI